export const createOrderRequestSchema = {
    type: "object",
    required: [
        "shippingType",
        "address",
        "city",
        "state",
        "postcode",
        "userId",
        "firstName",
        "lastName",
        "email",
        "cardNumber",
        "expiryDate",
        "cvv",
    ],
    properties: {
        _id: { type: "string", minLength: 1 },
        shippingType: { type: "string", enum: ["Standard", "Express"] },
        address: { type: "string" },
        city: { type: "string" },
        state: { type: "string" },
        postcode: { type: "string" },
        userId: { type: "string" },
        firstName: { type: "string" },
        lastName: { type: "string" },
        email: { type: "string" },
        cardNumber: { type: "string", minLength: 13, maxLength: 19 },
        expiryDate: { type: "string", pattern: "^(0[1-9]|1[0-2])\\/([0-9]{2})$" },
        cvv: { type: "string", minLength: 3, maxLength: 4 },
    },
};
